### ISSUE TITLE
Use other's work

### ISSUE THREAD

**Issue by hareldunn** [justinelliotmeyers/salvage_yard_atlas#1]
looking up salvage yard in Google Maps leads you to places you haven't mapped
I guess appending a city or county to the search will generate many results
![image](https://github.com/user-attachments/assets/6c7950e6-7ff9-4e41-b349-ff0ddb78af07)

**Comment by justinelliotmeyers** [comment]
this is loosely what i do. search empty locations in google earth for auto parts, auto salvage or just auto. trace, export, merge in.
